### ISSUE TITLE
NumpyDataGenerator for avoiding OOM GPU errors

### ISSUE THREAD

**Issue by davidslater** [Trusted-AI/adversarial-robustness-toolbox#1926]
**Is your feature request related to a problem? Please describe.**
Currently, if you have large numpy arrays in CPU memory and call a tensorflow estimator's `fit` method, the preprocessing will make them into tensors (https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/fa5a0c4c9dbbdec966713849dd34fc7321544839/art/estimators/tensorflow.py#L185) and then back to numpy arrays. This can cause OOM errors for very large numpy arrays.

An alternative would be to call `fit_generator`, which would avoid the OOM errors; however, it is unclear how to create a generator that is directly backed by Numpy arrays.

**Describe the solution you'd like**
I suggest the creation of a NumpyDataGenerator that is backed by numpy arrays. Then, if someone is hitting OOM errors doing
```
tf_classifier.fit(x, y, batch_size=batch_size, nb_epochs=nb_epochs, shuffle=True, **kwargs)
```
You could instead do:
```
tf_classifier.fit_generator(NumpyDataGenerator(x, y, batch_size=batch_size, shuffle=True), nb_epochs=nb_epochs, **kwargs)
```

**Comment by davidslater** [comment]
If this is of interest, I have a candidate implementation.

**Comment by beat-buesser** [comment]
Hi @davidslater I think that's an important issue that we should solve and your solution would be most welcome. One question to better understand the issue, why does decreasing `batch_size` in `.fit()` not avoid the issue?

**Comment by beat-buesser** [comment]
Would you have a small code example that reproduces the issue with open/random data?

**Comment by davidslater** [comment]
Batch size doesn't take effect until after preprocessing is applied to the entire input vector:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/fa5a0c4c9dbbdec966713849dd34fc7321544839/art/estimators/classification/tensorflow.py#L290

Batching happens later on the preprocessed vectors here:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/fa5a0c4c9dbbdec966713849dd34fc7321544839/art/estimators/classification/tensorflow.py#L305

Yeah, I can work to reproduce it. It will depend on the size on the GPU you're testing on.

**Comment by davidslater** [comment]
A different fix would be to apply the preprocessing in the batch loop of `fit`. However, this probably will have significantly lower efficiency for fitting, as the preprocessing and mapping to GPU would have to happen per batch.

**Comment by davidslater** [comment]
I think this should enable you to replicate. You will need to set the `gpu_memory` value to the GPU you are using, and you will also need to make sure there is sufficient CPU memory to store the numpy arrays.

```python
import numpy as np                                                                       
import tensorflow as tf                                                                  
from tensorflow import keras                                                             
from art.estimators.classification import TensorFlowV2Classifier                         
                                                                                         
num_examples = 100000                                                                    
input_shape = (224, 224, 3)                                                              
classes = 10                                                                             
dtype = np.float32                                                                       
gpu_size_per_sample = input_shape[0] * input_shape[1] * input_shape[2] * 4  # dtype      
                                                                                         
# NOTE: change this to your own GPU memory size                                          
gpu_memory = 24 * 2**30  # 24 GB                                                         
                                                                                         
num_examples = (gpu_memory // gpu_size_per_sample) + 1                                   
print(f"{num_examples} examples")                                                        
                                                                                         
                                                                                         
model = keras.applications.ResNet50(                                                     
    weights=None,                                                                        
    input_shape=input_shape,                                                             
    classes=classes,                                                                     
)                                                                                        
loss_object = tf.keras.losses.SparseCategoricalCrossentropy()                            
model.compile(                                                                           
    optimizer=tf.keras.optimizers.Adam(),                                                
    loss=loss_object,                                                                    
    metrics=["accuracy"],                                                                
)                                                                                        
                                                                                         
def train_step(model, samples, labels):                                                  
    with tf.GradientTape() as tape:                                                      
        predictions = model(samples, training=True)                                      
        loss = loss_object(labels, predictions)                                          
    gradients = tape.gradient(loss, model.trainable_variables)                           
    model.optimizer.apply_gradients(zip(gradients, model.trainable_variables))           
                                                                                         
art_classifier = TensorFlowV2Classifier(
    model=model,                                                                         
    loss_object=loss_object,                                                             
    train_step=train_step,                                                               
    nb_classes=classes,                                                                  
    input_shape=input_shape,                                                             
)                                                                                        
                                                                                         
print("Creating large numpy arrays")                                                     
y = np.arange(num_examples) % classes                                                    
x = np.random.random((num_examples,) + input_shape)                                      
                                                                                         
print("Calling TensorFlowV2Classifier.fit")                                              
art_classifier.fit(x, y, nb_epochs=1, verbose=True)
```

**Comment by beat-buesser** [comment]
Thank you! The script works for me in reproducing the issue. I have tested `TensorFlowV2DataGenerator` which seems to have a similar issue for this large array. I think your proposal makes sense.

I agree on your point about applying preprocessing to the mini-batch, it might also change the expected behavior if a existing preprocessors expect statistics over the entire dataset.

Would you like to open a pull request with the proposed `NumpyDataGenerator`?

**Comment by davidslater** [comment]
Sure, I can make a PR

**Comment by davidslater** [comment]
Is there a good place to add this to docs or tests?

**Comment by beat-buesser** [comment]
@davidslater I think the module docstring in `art.data_generators` starting line 18 could be a good place for additional documnetation, it will be shown at the top of https://adversarial-robustness-toolbox.readthedocs.io/en/latest/modules/data_generators.html. New tests should go to `tests/test_data_generators.py`
